"""
Hybrid Speculative Pipeline — MDLM drafts, Qwen3 refines.

THE CORRECT APPROACH (after v1 and v2 failed):

  v1: MDLM regenerates bad tokens with oracle bias → ruido (Δ=-0.02)
  v2: Oracle token replacement → rompe vocabulario (Δ=-0.71)
  
  v3 (THIS): Segment-level speculative decoding
    1. MDLM generates full text FAST (60K TPS, ~3s for 64 tokens)
    2. Qwen3 verifies by computing per-token acceptance probability
    3. Segments where Qwen3 disagrees → Qwen3 regenerates that segment
    4. Output: fast MDLM draft + Qwen3 quality where needed

KEY INSIGHT:
  Don't operate at TOKEN level across vocabularies.
  Operate at SEGMENT level: decode text, identify bad spans,
  have Qwen3 generate replacement text, re-encode for output.

SPEED:
  - MDLM draft: ~3s (parallel, all tokens at once)
  - Qwen3 verify: ~0.05s (single forward pass)
  - Qwen3 regen bad segments: ~0.5-1s (short AR generation)
  - Total: ~3.5-4s (vs Qwen3 alone: ~5s for 64 tokens)

  The speedup comes from MDLM handling MOST of the text,
  with Qwen3 only intervening where needed.
"""
import sys
import time
import math
from pathlib import Path
from typing import Tuple, List, Dict

import torch
import torch.nn.functional as F
import numpy as np

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

from ar_oracle_hrm import load_oracle, build_token_alignment, generated_region


class HybridSpeculative:
    """Hybrid MDLM+Qwen3 speculative pipeline.

    1. MDLM generates a fast draft
    2. Qwen3 verifies each segment
    3. Bad segments are regenerated by Qwen3
    """

    def __init__(
        self,
        mdlm_model,
        mdlm_tokenizer,
        oracle_model_name: str = "Qwen/Qwen3-0.6B",
        segment_size: int = 8,  # tokens per segment
        surprise_threshold: float = 1.5,
        max_regen_fraction: float = 0.5,
        oracle_temp: float = 0.6,
    ):
        self.mdlm = mdlm_model
        self.mdlm_tok = mdlm_tokenizer
        self.oracle, self.oracle_tok = load_oracle(oracle_model_name)
        self.segment_size = segment_size
        self.surprise_threshold = surprise_threshold
        self.max_regen_fraction = max_regen_fraction
        self.oracle_temp = oracle_temp

    @torch.no_grad()
    def verify_and_refine(
        self,
        tokens: torch.Tensor,  # [1, seq_len] MDLM tokens
        prompt_len: int = 0,
    ) -> Tuple[torch.Tensor, dict]:
        """Verify MDLM draft with Qwen3, regenerate bad segments.

        Args:
            tokens: [1, seq_len] generated MDLM tokens
            prompt_len: prompt tokens preserved

        Returns:
            refined_text: str (final coherent text)
            stats: dict
        """
        mask_id = self.mdlm_tok.mask_id
        pad_id = self.mdlm_tok.pad_id

        # 1. Decode MDLM text
        all_ids = tokens[0].cpu().tolist()
        clean_ids = [t for t in all_ids if t not in (mask_id, pad_id)]

        # Split prompt and generated text
        prompt_ids = clean_ids[:prompt_len] if prompt_len <= len(clean_ids) else clean_ids
        gen_ids = clean_ids[prompt_len:] if prompt_len < len(clean_ids) else []

        prompt_text = self.mdlm_tok.decode(prompt_ids)
        gen_text = self.mdlm_tok.decode(gen_ids)
        full_text = prompt_text + gen_text

        if not gen_text.strip():
            return tokens, {"error": "empty_generation"}

        # 2. Score with Qwen3 (teacher forcing)
        oracle_ids = self.oracle_tok.encode(full_text, add_special_tokens=False)
        oracle_input = torch.tensor([oracle_ids], device=DEVICE)
        logits = self.oracle(oracle_input).logits
        log_probs = F.log_softmax(logits.float(), dim=-1)

        # Per-token log-prob
        actual_next = oracle_input[0, 1:]
        predicted = log_probs[0, :-1]
        token_lps = predicted.gather(1, actual_next.unsqueeze(1)).squeeze(1)

        # 3. Map oracle positions to character ranges
        enc = self.oracle_tok(full_text, return_offsets_mapping=True,
                              add_special_tokens=False)
        oracle_offsets = enc["offset_mapping"]

        # 4. Segment the generated text
        gen_char_start = len(prompt_text)
        gen_char_end = len(full_text)

        # Score per segment
        segments = self._segment_and_score(
            gen_text, gen_char_start, oracle_offsets, token_lps
        )

        # 5. Find segments that need regeneration
        all_lps = [s["mean_lp"] for s in segments]
        if not all_lps:
            return tokens, {"error": "no_segments"}

        mean_lp = np.mean(all_lps)
        threshold = mean_lp - self.surprise_threshold

        bad_segments = [s for s in segments if s["mean_lp"] < threshold]

        # Cap regeneration
        max_regen = int(self.max_regen_fraction * len(segments))
        if len(bad_segments) > max_regen:
            bad_segments.sort(key=lambda s: s["mean_lp"])
            bad_segments = bad_segments[:max_regen]

        if not bad_segments:
            return tokens, {
                "segments": len(segments),
                "regenerated": 0,
                "mean_lp_before": mean_lp,
                "mean_lp_after": mean_lp,
            }

        # 6. Regenerate bad segments with Qwen3
        regen_count = 0
        new_gen_parts = []
        gen_pos = 0

        for seg in segments:
            if seg in bad_segments:
                # Regenerate this segment with Qwen3
                # Context = everything before this segment
                context_text = prompt_text + gen_text[:seg["gen_start"]]
                context_ids = self.oracle_tok.encode(
                    context_text, add_special_tokens=False
                )
                context_tensor = torch.tensor([context_ids], device=DEVICE)

                # Generate replacement
                n_tokens = max(1, len(seg["text"]) // 3)  # rough char→token
                n_tokens = min(n_tokens, self.segment_size)

                with torch.no_grad():
                    attention_mask = torch.ones_like(context_tensor)
                    out = self.oracle.generate(
                        context_tensor,
                        max_new_tokens=n_tokens,
                        do_sample=True,
                        temperature=self.oracle_temp,
                        top_p=0.9,
                        attention_mask=attention_mask,
                        pad_token_id=self.oracle_tok.eos_token_id,
                    )
                new_text = self.oracle_tok.decode(
                    out[0][len(context_ids):], skip_special_tokens=True
                ).strip()
                new_gen_parts.append(new_text)
                regen_count += 1
            else:
                # Keep original MDLM text
                new_gen_parts.append(seg["text"])

        # 7. Build final text
        final_gen_text = " ".join(new_gen_parts)
        final_text = prompt_text + " " + final_gen_text

        # 8. Re-score final text
        final_ids = self.oracle_tok.encode(final_text, add_special_tokens=False)
        final_input = torch.tensor([final_ids], device=DEVICE)
        with torch.no_grad():
            final_logits = self.oracle(final_input).logits
            final_lp = F.log_softmax(final_logits.float(), dim=-1)
            final_next = final_input[0, 1:]
            final_pred = final_lp[0, :-1]
            final_token_lps = final_pred.gather(
                1, final_next.unsqueeze(1)
            ).squeeze(1)

        # Map final log-prob back to generated region
        final_enc = self.oracle_tok(
            final_text, return_offsets_mapping=True, add_special_tokens=False
        )
        final_offsets = final_enc["offset_mapping"]
        final_gen_start = len(prompt_text)

        # Average LP of generated region
        gen_lps = []
        for o_start, o_end in final_offsets:
            if o_start >= final_gen_start and o_start < len(final_text):
                o_idx = None
                for i, (s, e) in enumerate(final_offsets):
                    if s == o_start:
                        o_idx = i
                        break
                if o_idx is not None and o_idx < len(final_token_lps):
                    gen_lps.append(final_token_lps[o_idx].item())

        final_mean_lp = np.mean(gen_lps) if gen_lps else mean_lp

        return final_text, {
            "segments": len(segments),
            "regenerated": regen_count,
            "mean_lp_before": mean_lp,
            "mean_lp_after": float(final_mean_lp),
            "lp_improvement": float(final_mean_lp) - mean_lp,
            "bad_segments": [{"text": s["text"][:40], "lp": s["mean_lp"]}
                            for s in bad_segments],
        }

    def _segment_and_score(
        self, gen_text, gen_char_start, oracle_offsets, token_lps
    ) -> List[dict]:
        """Segment generated text into chunks and score each."""
        segments = []
        text_len = len(gen_text)

        # Segment by segment_size words (more natural than chars)
        words = gen_text.split()
        if not words:
            return []

        words_per_seg = max(3, self.segment_size // 2)

        word_idx = 0
        while word_idx < len(words):
            seg_words = words[word_idx:word_idx + words_per_seg]
            seg_text = " ".join(seg_words)
            word_idx += words_per_seg

            # Find oracle tokens covering this segment's char range
            seg_gen_start = gen_text.find(seg_text)
            if seg_gen_start == -1:
                continue
            seg_char_start = gen_char_start + seg_gen_start
            seg_char_end = seg_char_start + len(seg_text)

            # Find oracle positions in this range
            seg_lps = []
            for i, (o_start, o_end) in enumerate(oracle_offsets):
                if o_start >= seg_char_end:
                    break
                if o_end > seg_char_start and i < len(token_lps):
                    seg_lps.append(token_lps[i].item())

            if seg_lps:
                mean_lp = np.mean(seg_lps)
            else:
                mean_lp = 0.0

            segments.append({
                "text": seg_text,
                "gen_start": seg_gen_start,
                "mean_lp": mean_lp,
                "n_tokens": len(seg_lps),
            })

        return segments
